name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t marlon11595/my-shiny-app .

    - name: Push Docker image
      run: docker push marlon11595/my-shiny-app

    - name: Deploy to GitHub Pages
      run: |
        docker run -d -p 3838:3838 marlon11595/my-shiny-app
        echo "Your app is now running on GitHub Pages"
